### **Question** **4**

In [0]:
import pandas as pd
import numpy as np
from queue import Queue
import random

**Data**

In [0]:
df = pd.read_csv('/content/drive/My Drive/Datasets/Question-4/weather.csv')
df = df.rename({"Apparent Temperature (C)": "output"}, axis=1)
label=df['output'].values
df=df.drop(["Formatted Date","Daily Summary","output"],axis=1)
mode_masType = df['Precip Type'].mode()[0]
df = df.fillna({'Precip Type':mode_masType})

mode_masType = df['Summary'].mode()[0]
df = df.fillna({'Summary':mode_masType})


mode_masType = df['Temperature (C)'].mean()
df = df.fillna({'Temperature (C)':mode_masType})

mode_masType = df['Humidity'].mean()
df = df.fillna({'Humidity':mode_masType})

mode_masType = df['Wind Speed (km/h)'].mean()
df = df.fillna({'Wind Speed (km/h)':mode_masType})

mode_masType = df['Wind Bearing (degrees)'].mean()
df = df.fillna({'Wind Bearing (degrees)':mode_masType})

mode_masType = df['Visibility (km)'].mean()
df = df.fillna({'Visibility (km)':mode_masType})

mode_masType = df['Pressure (millibars)'].mean()
df = df.fillna({'Pressure (millibars)':mode_masType})


df = pd.concat([df,pd.get_dummies(df['Summary'], prefix='Summary')],axis=1)
df = pd.concat([df,pd.get_dummies(df['Precip Type'], prefix='Precip Type')],axis=1)
df.drop(['Summary','Precip Type'],axis=1, inplace=True)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data=df.values
scaler.fit(data)
data=scaler.transform(data)
df=pd.DataFrame(data)
df.insert(0,'One_Padding',1)

**Data After Normalizing**

In [28]:
df

       One_Padding         0     1         2         3  ...   29   30   31   32   33
0                1  0.506975  0.89  0.221130  0.699164  ...  0.0  0.0  0.0  1.0  0.0
1                1  0.505085  0.86  0.223399  0.721448  ...  0.0  0.0  0.0  1.0  0.0
2                1  0.505445  0.89  0.061523  0.568245  ...  0.0  0.0  0.0  1.0  0.0
3                1  0.487805  0.83  0.220877  0.749304  ...  0.0  0.0  0.0  1.0  0.0
4                1  0.495365  0.83  0.172970  0.721448  ...  0.0  0.0  0.0  1.0  0.0
...            ...       ...   ...       ...       ...  ...  ...  ...  ...  ...  ...
77280            1  0.820718  0.32  0.191125  0.058496  ...  0.0  0.0  0.0  1.0  0.0
77281            1  0.774998  0.43  0.172214  0.086351  ...  0.0  0.0  0.0  1.0  0.0
77282            1  0.751778  0.48  0.158094  0.055710  ...  0.0  0.0  0.0  1.0  0.0
77283            1  0.710557  0.56  0.140696  0.083565  ...  0.0  0.0  0.0  1.0  0.0
77284            1  0.702187  0.60  0.164902  0.055710  ...  0.0  0.0  0.0  1.0  0.0

[77285 rows x 35 columns]

In [0]:
data=df.values

In [43]:
from random import random
theta=[]
for i in range(df.shape[1]):
  theta.append(random())
print(theta)
theta=np.array(theta).reshape([1,len(theta)])
label=label.reshape([label.shape[0],1])

[0.6532403503085085, 0.8904646412777778, 0.23286736159367172, 0.2191774442063803, 0.5884702055118414, 0.6991143217264353, 0.8359176692642546, 0.8874625486027603, 0.5075828722842738, 0.9589537806801148, 0.8968629371042766, 0.7670081853211405, 0.6810666865141649, 0.2589785071444234, 0.4259952193260641, 0.3860438281460623, 0.3736818250478213, 0.7421848054843733, 0.9466888017092508, 0.5802634487042932, 0.5016317447839093, 0.30318042415490587, 0.6697065037113973, 0.28345478454828543, 0.2965182369421382, 0.12050672947113583, 0.5478862212888657, 0.11183671897675207, 0.3292768371548618, 0.844484819764596, 0.5104708461604346, 0.41757293598024603, 0.8391271393195705, 0.08999173937071758, 0.004069761779559311]

In [0]:
def cost_f(pre,label):
  sum=0
  for i in range(label.shape[0]):
    sum = sum +(pre[i]-label[i])*(pre[i]-label[i])
  return sum/(2* pre.shape[0])

In [0]:
def MAE(pre,label):
  sum=0
  for i in range(label.shape[0]):
    sum = sum +abs(pre[i]-label[i])
  return sum/(pre.shape[0])

In [0]:
def grad(theta,pre,label,X):
  alpha=0.1
  error=(pre-label)
  theta=theta - alpha * (np.dot(np.transpose(error),data)/label.shape[0])
  return theta

**Mean Square Error**

In [50]:
k=True
old=0
for i in range(2000):
  value=np.dot(theta,np.transpose(data))
  value=value.reshape([label.shape[0],1])
  theta=grad(theta,value,label,data)
  value=np.dot(theta,np.transpose(data))
  value=value.reshape([label.shape[0],1])
  new = cost_f(value,label)
  if(k):
      old=new
      k=False
  elif(old<=new):
      break
  else:
      old=new
from sklearn.metrics import r2_score
print(r2_score(label,value))

0.9837383494157305

**Mean Absolute Error**

In [48]:
k=True
old=0
for i in range(1000):
  value=np.dot(theta,np.transpose(data))
  value=value.reshape([label.shape[0],1])
  theta=grad(theta,value,label,data)
  value=np.dot(theta,np.transpose(data))
  value=value.reshape([label.shape[0],1])
  new = MAE(value,label)
  if(k):
      old=new
      k=False
  elif(old<=new):
      break
  else:
      old=new
from sklearn.metrics import r2_score
print(r2_score(label,value))

0.9350016933462093